#!/bin/bash
#BSUB -J petsc-solve-1D-HeatEquation
#BSUB -q ser
#BSUB -n 4
#BSUB -e log
#BSUB -o log

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun ./solve.out -dt 0.001 -log_view > log_view 2>&1
