#!/bin/bash
#BSUB -J petsc-HeatEquation
#BSUB -q ser
#BSUB -n 10
#BSUB -e log
#BSUB -o log

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun ./solve.out -dt 0.01 -t 10.0 -state 0 -log_view>log_view
